version: "3"

networks:
  dockervlan:
    external: true
    
volumes:
  pihole:    
  dnsmasq.d:
  unbound:  
    
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"     
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: PASSWORD
      PIHOLE_DNS_: 192.168.178.195;192.168.178.193
      ServerIP: 192.168.178.193     
    security_opt:
      - no-new-privileges:true
    volumes:
      - 'pihole:/etc/pihole'
      - 'dnsmasq.d:/etc/dnsmasq.d'    
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 192.168.178.195
      - 192.168.178.193
    networks:
      dockervlan:
        ipv4_address: 192.168.178.193    
        
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    hostname: unbound
    volumes:
      - unbound:/opt/unbound/etc/unbound
    ports:
      - 53/tcp
      - 53/udp
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: 192.168.178.195