version: '3'

networks:
  dockervlan:
    external: true

volumes:
  jopdb:

services:
  db:
    image: postgres:latest
    container_name: joplindb
    volumes:
      - jopdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=a23ka2ck3"3ca2oi3c
      - POSTGRES_USER=joplin
      - POSTGRES_DB=joplindb
    networks:
      dockervlan:
        ipv4_address: 192.168.178.204

  app:
    image: joplin/server:latest
    container_name: joplin
    depends_on:
      - db
    ports:
      - "22300:22300"
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=http://192.168.68.205:22300
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=a23ka2ck3"3ca2oi3c
      - POSTGRES_DATABASE=joplindb
      - POSTGRES_USER=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=192.168.178.204
    networks:
      dockervlan:
        ipv4_address: 192.168.178.205