volumes:
  data:

networks:
  dockervlan:
    external: true

services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    ports:
      - "5800:5800"
    volumes:
      - data:/config
      - "/mnt/media/Downloads:/output:rw"
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: 192.168.178.242
