volumes:
    data:

networks:
    dockervlan:
        external: true

services:
    gotify:
        container_name: gotify
        image: gotify/server:latest
        volumes:
            - data:/app/data
        restart: unless-stopped
        environment:
            - TZ="Europe/Berlin"
        networks:
            dockervlan:
                ipv4_address: 192.168.178.210
