version: '3'

volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  dockervlan:
    external: true

services:
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    volumes:
      - /home/docker/nextcloud/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=STRONGPASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
    networks:
      dockervlan:
        ipv4_address: 192.168.178.201

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - /home/docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=STRONGPASSWORD
      - MYSQL_PASSWORD=STRONGPASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      dockervlan:
        ipv4_address: 192.168.178.202