version: '3'

networks:
  dockervlan:
    external: true

volumes:
  data:

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 9999:80
    volumes:
      - data:/etc/phpmyadmin/
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: 192.168.178.199
