version: '3'

networks:
  dockervlan:
    external: true

volumes:
  content:
  db:
  myphpadmin:
    
services:
  wordpress-app:
    image: wordpress:latest
    container_name: wordpress-app
    volumes: 
      - content:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - wordpress-db
    environment:
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_PASSWORD=strongpassword"
      - "WORDPRESS_DB_HOST=192.168.178.198"
      - "WORDPRESS_TABLE_PREFIX=wp_"
      - "WORDPRESS_DB_NAME:wordpress" 
    dns: 192.168.178.193
    networks:
      dockervlan:
        ipv4_address: 192.168.178.197
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  wordpress-db:
    image: mariadb:latest
    container_name: wordpress-db
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=strongpassword"
      - "MYSQL_PASSWORD=strongpassword"
      - "MYSQL_USER=wordpress"
      - "MYSQL_DATABASE=wordpress"     
    networks:
      dockervlan:
        ipv4_address: 192.168.178.198
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 9999:80
    depends_on:
      - wordpress-db
    volumes:
      - myphpadmin:/etc/phpmyadmin/
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: 192.168.178.199
