version: '3'

networks:
  dockervlan:
    external: true
    
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes: 
      - /home/docker/wp:/var/www/html
    ports:
      - 80:80
    environment:
      - "WORDPRESS_DB_USER=root"
      - "WORDPRESS_DB_PASSWORD=STRONGPW"
    dns: 192.168.178.200
    networks:
      dockervlan:
        ipv4_address: 192.168.178.197
    security_opt:
      - no-new-privileges:true
    restart: always

  mysql:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - /home/docker/wp/wp-db:/var/lib/mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=STRONGPW"
      - "MYSQL_DATABASE=wordpress"
    networks:
      dockervlan:
        ipv4_address: 192.168.178.198
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 9999:80
    volumes:
      - /home/docker/wp/myphpadmin
    restart: always
    networks:
      dockervlan:
        ipv4_address: 192.168.178.199