version: '3.5'

networks:
  dockervlan:
    external: true

volumes:
  data:
  db:
  
services:
  postgres:
    image: postgres:latest
    container_name: linkwardendb
    env_file: .env
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    container_name: linkwarden
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: unless-stopped
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 3000:3000
    volumes:
      - data:/data/data
    depends_on:
      - postgres
    security_opt:
     - no-new-privileges:true
    networks:
      dockervlan:
        ipv4_address: 192.168.178.211
