networks:
  dockervlan:
    external: true

volumes:
  cache:
  config:

services:
    jellyfin:
        image: 
            'jellyfin/jellyfin:latest'
        container_name:
            jellyfin
        volumes:
            - 'config:/config'
            - 'cache:/cache'
            - '/mnt/media/:/media'
            - '/dev/shm:/data/transcode' # Offload transcoding to RAM if you have enough RAM
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Berlin
          - JELLYFIN_PublishedServerUrl=192.168.178.222
        ports:
          - 8096:8096
          - 8920:8920 #optional
          - 7359:7359/udp #optional
          - 1900:1900/udp #optional
        restart: 
            unless-stopped
        security_opt:
            - no-new-privileges:true  
        networks: 
            dockervlan:
                ipv4_address: 192.168.178.222
